import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Clients from "../components/Clients";
import Contacts from "../components/Contacts";
import Delivery from "../components/Delivery";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
// HACK: Add framer-motion as dependecy

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Frutodom</title>
        <meta name="description" content="Generated by Domeh John Kelvin" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto 3xl:max-w-[1920px]">
        <Navbar />
        <Hero />
        <About />
        <Delivery />
        <Clients />
        <Contacts />
      </div>
    </>
  );
};

export default Home;
